config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  resources :tasks, only: [:create, :edit, :destroy, :update]
  get 'users/new'

  root 'static_pages#home'
  get 'static_pages/help'
  get 'static_pages/about'

  get 'about' => 'static_pages#about'
  get 'help' => 'static_pages#help'
  get 'contact' => 'static_pages#contact'
  get 'tasks/:id/create_share', to: 'tasks#create_share', as: 'create_share'
  post 'share' => 'tasks#share'
  
  get 'signup' => 'users#new'

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
    render text: "hello world!"
  end

  def after_sign_in_path_for(user)
    user
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end

  def sign_up(resource_name, resource)

  end

  def after_sign_up_path_for(resource)
    root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy, :edit]
  before_action :correct_user, only: [:destroy]

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:success] = "Task created!"
      # redirect_to root_url
      redirect_to current_user
    else
      # render 'static_pages/home'
      flash[:danger] = "Task can't be blank or longer than 140 characters"
      redirect_to current_user
    end
  end

  def destroy
    @task.destroy
    flash[:success] = "Task deleted"
    redirect_to current_user
  end

  def edit
    @tasks = current_user.tasks.paginate(page: params[:page], per_page: 5)
    @task = @tasks.find_by(id: params[:id])
    @user = current_user
  end

  def update
    @user = current_user
    @task = current_user.tasks.find_by(id: params[:id])
    if @task.update_attributes(task_params) && !@task.nil?
      flash[:success] = "Task updated"
      redirect_to @user
    else
      flash[:danger] = "Task can't be blank or longer than 140 characters"
      redirect_to @user
    end
  end

  def create_share
    @email = ""
    @task = current_user.tasks.find_by(id: params[:id])
  end

  def share
    @user = User.find_by(email: params[:email])
    if @user
      @task = @user.tasks.build(content: params[:content], user: current_user)
      if @task.save
        flash.now[:success] = "Task created!"
        # redirect_to root_url
        redirect_to current_user
      else
        # render 'static_pages/home'
        flash.now[:danger] = "Task can't be blank or longer than 140 characters"
        redirect_to current_user
      end
    else
      flash[:danger] = "User with current email not found!"
      redirect_to current_user
    end
  end

  private

  def task_params
    params.require(:task).permit(:content)
  end

  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    redirect_to current_user if @task.nil?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only: [:index, :edit, :update, :destroy]


  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks.paginate(page: params[:page], per_page: 5)
    @task = current_user.tasks.build if user_signed_in?
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # log_in @user
      # flash[:success] = "Welcome to the Sample App!"
      # redirect_to @user
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    # @user = User.find_by(params[:id])

    @user = current_user
  end

  def update
    # @user = User.find(params[:id])
    @user = current_user
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    user = User.find(params[:id]).destroy
    flash[:success] = "User #{user.name} deleted"
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless (@user == current_user)
  end

  # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/devise_helper.rb
module DeviseHelper

  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
      <div class = "alert alert-danger">
        <h2>#{sentence}</h2>
        <ul>#{messages}</ul>
      </div>
    HTML

    html.html_safe
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar", size: size)
  end

  def current_user?(user)
    user == current_user
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    User tasks app, by Mykola Kovalchuk
  </small>
  <nav>
    <ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse header">
  <div class="container">
    <%= link_to "user tasks", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if user_signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user[:name]%> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
  <div id="underheader">
  </div>
</header>

app/views/layouts/_message.html.erb
<% flash.each do |message_type, message|%>
    <%case message_type%>
<%when "notice"%>
        <div class="alert alert-success"><%= notice %></div>
    <%when "alert"%>
        <div class="alert alert-danger"><%= alert %></div>
    <%end%>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <%= render 'layouts/message' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_task_form.html.erb
<%= form_for(@task) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= f.text_area :content, placeholder: "Compose new task..." %>
    </div>
    <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.tasks.count, "task") %></span>

app/views/static_pages/about.html.erb
<% provide(:title, "About")%>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact")%>
<h1>Contact page</h1>

app/views/static_pages/help.html.erb
<% provide(:title, "Help")%>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home")%>

<div class="center jumbotron">
  <h1>Welcome to the User Tasks App</h1>

  <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
</div>

<%= image_tag("task.png", alt: "Task logo")%>

app/views/tasks/_task.html.erb
<li id="task-<%= task.id %>">
  <%= link_to gravatar_for(task.user, 50), task.user %>
  <span class="user"><%= link_to task.user.name, task.user %></span>
  <span class="content"><%= task.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(task.created_at) %> ago.  |
    <% if current_user == @user %>
        <%= link_to "delete", task, method: :delete,
                    data: { confirm: "Are you sure?" },
                    class: "delete-part"%>  |
        <%= link_to "edit", edit_task_path(task.id)%>  |
        <%= link_to "share", create_share_path(task.id)%>
    <% end %>
  </span>
</li>

app/views/tasks/create_share.html.erb
<% provide(:title, "Create share") %>
<h1>Share post</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @email, url: {action: "share"} do |f| %>

        <%= hidden_field_tag :task, @task %>
        <%= f.label :email %>
        <%= f.email_field :email, placeholder: "Enter email" %>
        <%= f.text_field :content, value: @task.content %>

        <%= f.submit "Share", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user, 100 %>
        <%= @user.name %>
      </h1>
    </section>
    <%if current_user == @user%>
        <section class="task_form">
            <%= form_for(@task) do |f| %>
                <%= render 'shared/error_messages', object: f.object %>
                <div class="field">
                  <%= f.text_area :content %>
                </div>
                <%= f.submit "Update", class: "btn btn-primary" %>
            <% end %>
        </section>
    <% end %>
  </aside>
  <div class="col-md-8">
    <% if @user.tasks.any? %>
        <h3>Tasks (<%= @user.tasks.count %>)</h3>
        <ol class="tasks">
          <%= render @tasks %>
        </ol>
        <%= will_paginate @tasks %>
    <%end%>
  </div>
</div>

app/views/users/_user.erb
<li>
    <div class="user-image"><%= gravatar_for user, 50%></div>
    <%= link_to user.name, user %>
  <% if current_user.has_role?(:admin) && !current_user?(user)%>
      <span> | </span>
      <%= link_to "delete", user, method: :delete,
                  data: { confirm: "Are you sure?" },
                  class: "delete-part"%>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object%>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user, 50 %>
      <a href="http://gravatar.com/emails" target=_blank>change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users%>
</ul>

<%= will_paginate %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user, 100 %>
        <%= @user.name %>
      </h1>
    </section>
    <%if current_user == @user%>
        <section class="task_form">
          <%= render 'shared/task_form' %>
        </section>
    <% end %>
  </aside>
  <div class="col-md-8">
    <% if @user.tasks.any? %>
        <h3>Tasks (<%= @user.tasks.count %>)</h3>
        <ol class="tasks">
          <%= render @tasks %>
        </ol>
        <%= will_paginate @tasks %>
    <%end%>
  </div>
</div>